name: Master Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: composer install --no-suggest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy Passport Keys
        run: |
          aws s3 sync s3://elasticbeanstalk-us-east-1-839729112102/oauth/api storage/keys

      - name: Zip Project
        id: zip-project
        run: zip -r deploy.zip .

      - name: Get Commit Hash
        id: version-hash
        run: |
          echo "::set-output name=hash::${GITHUB_SHA}"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_IAM_KEY }}
          aws_secret_key: ${{ secrets.AWS_IAM_SECRET }}
          application_name: ${{ secrets.AWS_EB_APP }}
          environment_name: ${{ secrets.AWS_EB_ENV }}
          version_label: ${{ steps.version-hash.outputs.hash }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip

      - name: Slack Notification
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.ARENA_API_SLACK_ENDPOINT }}
            --data-urlencode 'repo_owner=${{github.repository_owner}}'
            --data-urlencode 'repo=${{github.repository}}'
            --data-urlencode 'commit=${{github.sha}}'
            --data-urlencode 'status=${{job.status}}'
            --data-urlencode 'workflow=${{github.workflow}}'
            --data-urlencode 'actor=${{github.event.head_commit.author.username}}'
            --data-urlencode 'repo_url=${{github.event.repository.url}}'
        if: always()