name: Staging Deploy

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: composer install --no-suggest

      - name: Zip Project
        id: zip-project
        run: zip -r deploy.zip .

      - name: Get Commit Hash
        id: version-hash
        run: |
          echo "::set-output name=hash::${GITHUB_SHA}"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_IAM_KEY_STAGING }}
          aws_secret_key: ${{ secrets.AWS_IAM_SECRET_STAGING }}
          application_name: ${{ secrets.AWS_EB_APP_STAGING }}
          environment_name: ${{ secrets.AWS_EB_ENV_STAGING }}
          version_label: ${{ steps.version-hash.outputs.hash }}
          region: ${{ secrets.AWS_REGION_STAGING }}
          deployment_package: deploy.zip

      - name: Slack Notification
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.ARENA_API_SLACK_ENDPOINT }}
            --data-urlencode 'repo_owner=${{github.repository_owner}}'
            --data-urlencode 'repo=${{github.repository}}'
            --data-urlencode 'commit=${{github.sha}}'
            --data-urlencode 'status=${{job.status}}'
            --data-urlencode 'workflow=${{github.workflow}}'
            --data-urlencode 'actor=${{github.event.head_commit.author.username}}'
            --data-urlencode 'repo_url=${{github.event.repository.url}}'
        if: always()